// ─── Shared TypeScript types for the BodySync AI pipeline ───

/** Raw metrics extracted by OCR + parser */
export interface ParsedBCAData {
  height: number | null;
  weight: number | null;
  skeletalMuscleMass: number | null;
  bodyFatMass: number | null;
  bodyFatPercent: number | null;
  bmi: number | null;
  bmr: number | null;
  visceralFat: number | null;
  totalBodyWater: number | null;
  leanBodyMass: number | null;
  segmentalLean: SegmentalData | null;
  segmentalFat: SegmentalData | null;
}

export interface SegmentalData {
  rightArm: number | null;
  leftArm: number | null;
  trunk: number | null;
  rightLeg: number | null;
  leftLeg: number | null;
}

/** Computed ratios & assessment produced by the analysis engine */
export interface BodyCompositionAnalysis {
  // Computed ratios
  muscleToWeightRatio: number | null;
  fatToWeightRatio: number | null;
  leanBodyMass: number | null;
  leanMassPercent: number | null;
  fatMassPercent: number | null;
  bmiCategory: string;
  visceralFatCategory: string;

  // Muscle balance
  muscleBalance: MuscleBalance | null;

  // Textual insights
  overallStatus: string;
  muscleAnalysis: string;
  fatAnalysis: string;
  bmiInterpretation: string;
  visceralFatHealth: string;
  metabolismAnalysis: string;
  segmentalBalance: string;

  // Strategy
  trainingRecommendations: string;
  nutritionRecommendations: string;

  // Insight cards
  positiveIndicators: InsightCard[];
  areasToImprove: InsightCard[];
}

export interface MuscleBalance {
  upperLower: "balanced" | "upper-dominant" | "lower-dominant";
  leftRight: "balanced" | "left-dominant" | "right-dominant";
  description: string;
}

export interface InsightCard {
  title: string;
  description: string;
  type: "positive" | "warning" | "info";
  metric?: string;
}

/** Calorie & macro targets generated by the nutrition engine */
export interface NutritionTargets {
  maintenanceCalories: number;
  fatLossCalories: number;
  muscleGainCalories: number;
  protein: number; // grams
  carbs: number;
  fats: number;
  proteinPerKg: number;
  carbsPerKg: number;
  fatsPerKg: number;
}

/** The complete AI-generated plan */
export interface GeneratedPlan {
  calorieTarget: number;
  macros: { protein: number; carbs: number; fats: number };
  hydrationTarget: string;
  sleepRecommendation: string;
  workoutPlan: WorkoutDay[];
  nutritionTargets: NutritionTargets;
  mealPlan: MealPlan;
  bodyAnalysis: BodyCompositionAnalysis;
}

export interface WorkoutDay {
  day: string;
  focus: string;
  exercises: string[];
}

export interface MealPlan {
  meals: MealItem[];
  foodsToReduce: string[];
  foodsToPrioritize: string[];
}

export interface MealItem {
  name: string;
  time: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
}

/** OCR extraction result returned by /api/analyze-report */
export interface AnalysisResult {
  success: boolean;
  metrics: ParsedBCAData;
  rawText: string;
  confidence: number;
  warnings: string[];
}
